[package]
name = "rbrowserengine"
version = "0.1.0"
edition = "2021"

[dependencies]
# gfx = "0.18.3"
# gfx_text = "0.33.0"
# gfx_window_glutin = "0.31.0"
# glutin = "0.32.1"
gfx = "0.14.0"
gfx_text = "0.15.0"
gfx_window_glutin = "0.14.0"
glutin = "0.7.1"
