[package]
name = "rust-pastebin-yt"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.8.0"
rand = "0.8.5"
rusqlite = { version = "0.31.0", features = ["bundled"]}
serde = {version = "1.0.203", features = ["derive"]}
